myexe: myStrFunc.o myMainFunc.o myMain.o
	gcc -o myexe myStrFunc.o myMainFunc.o myMain.o
myStrFunc.o: myStrFunc.c
	gcc -c myStrFunc.c
myMainFunc.o: myMainFunc.c
	gcc -c myMainFunc.c
myMain.o: myMain.c
	gcc -c myMain.c
